### ISSUE TITLE
isPrime does not check if numbers are divisible by 5

### ISSUE THREAD

**Issue by freddyheppell** [Prabhakar-Poudel/random-prime#7]
This line means that isPrime doesn't check if the number is divisible by 5
https://github.com/Prabhakar-Poudel/random-prime/blob/de0a3deaf4071f3e2990a6233bf7d761885a17b4/index.js#L17

This means that calls which should not return true, e.g. `isPrime(235)` will return true.

**Comment by Prabhakar-Poudel** [comment]
Thanks for reporting. Will push a patch soon.

**Comment by freddyheppell** [comment]
Thanks for this fix, would you mind publishing a new version of this package?

I'd also suggest [deprecating](https://docs.npmjs.com/cli/deprecate) v1.0.0 to ensure people update.
